REPLACE INTO `category` (`id`, `name`, `type`) VALUES
	(1, 'Breakfast', 'RECIPE'),
	(2, 'Appetiser', 'RECIPE'),
	(3, 'Soup', 'RECIPE'),
	(4, 'Meat dish', 'RECIPE'),
	(5, 'Fish dish', 'RECIPE'),
	(6, 'Garnish', 'RECIPE'),
	(7, 'Salad/pickles', 'RECIPE'),
	(8, 'Pasta/dessert', 'RECIPE'),
	(9, 'gram', 'INGREDIENT'),
	(10, 'decagram', 'INGREDIENT'),
	(11, 'teaspoon', 'INGREDIENT'),
	(12, 'tablespoon', 'INGREDIENT'),
	(13, 'deciliter', 'INGREDIENT'),
	(14, 'piece', 'INGREDIENT'),
	(15, 'pinch', 'INGREDIENT');
